export const FONT_STYLE = <const>{
    BOLD: 'bold',
    ITALIC: 'italic',
    UNDERLINE: 'underline',
};

export const GENERAL_SCOPES = <const>[
    'button.background',
    'button.foreground',
    'button.hoverBackground',
    'editor.background',
    'editor.foreground',
    'editor.selectionBackground',
    'editor.selectionForeground',
    'editorGutter.background',
    'editorLineNumber.foreground',
    'focusBorder',
    'foreground',
    'input.background',
    'input.border',
    'input.foreground',
    'input.placeholderForeground',
    'list.focusBackground',
    'list.focusForeground',
    'list.hoverBackground',
    'list.hoverForeground',
    'panel.background',
    'panel.border',
    'quickInput.background',
    'quickInput.foreground',
    'sideBar.background',
    'sideBar.border',
    'sideBar.foreground',
    'statusBar.background',
    'statusBar.border',
    'statusBar.foreground',
    'statusBarItem.activeBackground',
    'statusBarItem.hoverBackground',
];
